server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.8.16.76:3306/db_sync?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    dbcp2:
      max-idle: 2
      max-total: 8
      default-auto-commit: false
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 600000
  redis:
    host: 200.200.200.52
    port: 6379
    database: 0
    password:
    jedis:
        pool:
          min-idle: 2
          max-idle: 10
          max-active: 20
          max-wait: 1000
      #cluster:
      #nodes: 集群
  mvc:
    static-path-pattern: /static/**
    #view:
      #prefix: /xxx/
      #suffix: .jsp
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  #dubbo:
    #application:
      #name: test-thomax
    #register:
      #address: zookeeper://200.200.200.55:2181
    #protocol:
      #name: clife-v4
      #port: 21029
    #scan: com.clife.sync.service.sync.interfaces #服务暴露与发现消费所在的package

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  #type-aliases-package: com.thomax.example.model  #别名扫描
  #config-location: classpath:mybatis/SqlMapConfig.xml  #加载Mybatis核心配置文件
  #spring.datasource.type=com.jolbox.bonecp.BoneCPDataSource  #配置连接池，还需要在pom.xml中加入该连接池的依赖

# Actuator Web REST 监控配置（在spring boot 2.0以后,actuator默认只开启了info和health两个端点,要想使用其他的端点需要如下配置）
management:
  endpoints:
    web:
      base-path: /actuator  # 访问根路径
      exposure:
        include: "*"

logging:
  level:
    root: info


